# Generated by Django 3.0.3 on 2020-02-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='i',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='j',
            field=models.IntegerField(default=0),
        ),
    ]
