# Generated by Django 3.0.3 on 2020-03-02 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200228_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='i',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='j',
            new_name='y',
        ),
    ]
