# Generated by Django 3.0.3 on 2020-03-02 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20200301_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='x',
            new_name='i',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='y',
            new_name='j',
        ),
    ]
