# Generated by Django 3.0.3 on 2020-03-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0006_world'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='currentWorld',
            field=models.IntegerField(default=0),
        ),
    ]
